application: xentineles
version: 1-0-1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /api/users.*
  script: main.APP

- url: /api/device.*
  script: main.APP

- url: /api/login.*
  script: main.APP

- url: /api/logged.*
  script: main.APP

- url: /(.*\.html)
  mime_type: text/html
  static_files: app/\1
  upload: app/(.*\.html)
  expiration: "1h"

- url: /(.*\.css)
  mime_type: text/css
  static_files: app/\1
  upload: app/(.*\.js)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: app/\1
  upload: app/(.*\.js)

- url: (.*)/(.*)
  static_files: app/index.html
  upload: app

# site root
- url: /
  static_files: app/index.html
  upload: app/index.html
  expiration: "15m"

libraries:
- name: webapp2
  version: latest